# Tcl script generated by PlanAhead

set tclUtilsPath "C:/Xilinx/14.1/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgProjectPath "C:/Users/azure/Desktop/repoMS/sase_project-master/Proyecto_MS/MS_final.srcs/sources_1/ip/div_gen_v3_0_0/coregen.cgc"

set ipName "Divider"

set hdlType "Verilog"

set cgPartSpec "6slx16-2csg324"

set chains "GENERATE_CURRENT_CHAIN"

set params ""

set bomFilePath "C:/Users/azure/Desktop/repoMS/sase_project-master/Proyecto_MS/MS_final.srcs/sources_1/ip/div_gen_v3_0_0/pa_cg_bom.xml"

# generate the IP
set result [source "C:/Xilinx/14.1/ISE_DS/PlanAhead/scripts/pa_cg_gen_core.tcl"]

exit $result

