# Tcl script generated by PlanAhead

set tclUtilsPath "C:/Xilinx/14.1/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgProjectPath "C:/Users/azure/Desktop/repoMS/sase_project-master/Proyecto_MS/MS_final.srcs/sources_1/ip/div_gen_v3_0_0/coregen.cgc"

set ipName "div_gen_v3_0_0"

set vlnv "xilinx.com:ip:div_gen:3.0"

set cgPartSpec "6slx16-2csg324"

set bomFilePath "C:/Users/azure/Desktop/repoMS/sase_project-master/Proyecto_MS/MS_final.srcs/sources_1/ip/div_gen_v3_0_0/pa_cg_bom.xml"

set hdlType "Verilog"

set chains "CUSTOMIZE_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

# configure the IP
set result [source "C:/Xilinx/14.1/ISE_DS/PlanAhead/scripts/pa_cg_config_core.tcl"]

exit $result

